# Generated by Django 3.2 on 2021-05-12 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(2)])),
                ('number', models.IntegerField(max_length=11, validators=[django.core.validators.MinLengthValidator(10, message='전화번호는 10,11 자리로 입력해주세요')])),
            ],
        ),
    ]
