# Generated by Django 3.2 on 2021-05-12 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='number',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10, message='전화번호는 10,11 자리로 입력해주세요')]),
        ),
    ]
