# Generated by Django 3.2 on 2021-05-12 10:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_alter_study_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='number',
        ),
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(2)])),
                ('number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10)])),
                ('study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.study')),
            ],
        ),
    ]
