# Generated by Django 3.2 on 2021-05-12 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20210512_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 19, 40, 23, 726329)),
        ),
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
