# Generated by Django 3.2 on 2021-05-12 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20210512_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 0, 15, 27, 738999)),
        ),
    ]
