# Generated by Django 3.2 on 2021-05-14 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_alter_student_first_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 17, 5, 4, 992739)),
        ),
    ]
