# Generated by Django 3.2 on 2021-05-16 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_auto_20210516_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='changed_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 16, 1, 23, 45, 237724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 16, 1, 23, 45, 237724, tzinfo=utc)),
        ),
    ]
