# Generated by Django 3.2 on 2021-05-21 04:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0015_auto_20210516_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Study',
        ),
        migrations.AlterField(
            model_name='student',
            name='changed_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 21, 4, 20, 17, 354065, tzinfo=utc), verbose_name='첫 참여날짜'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 21, 4, 20, 17, 354065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
