# Generated by Django 3.2 on 2021-05-22 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0016_auto_20210521_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fourth_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 6, 29, 23, 927437, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='student',
            name='plus_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 6, 29, 23, 927437, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='student',
            name='second_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 6, 29, 23, 927437, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='student',
            name='third_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 6, 29, 23, 927437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='changed_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 6, 29, 23, 927437, tzinfo=utc), verbose_name='첫 참여날짜'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 6, 29, 23, 927437, tzinfo=utc)),
        ),
    ]
