# Generated by Django 3.2 on 2021-05-22 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0018_auto_20210522_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='day2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='day3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='day4',
        ),
        migrations.AddField(
            model_name='student',
            name='fourth_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 7, 6, 41, 881893, tzinfo=utc), verbose_name='네번째 참여일'),
        ),
        migrations.AddField(
            model_name='student',
            name='second_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 7, 6, 41, 880889, tzinfo=utc), verbose_name='두번째 참여일'),
        ),
        migrations.AddField(
            model_name='student',
            name='third_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 7, 6, 41, 880889, tzinfo=utc), verbose_name='세번째 참여일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='changed_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 7, 6, 41, 881893, tzinfo=utc), verbose_name='첫 참여날짜'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 7, 6, 41, 880889, tzinfo=utc), verbose_name='첫번째 참여일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='plus_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 7, 6, 41, 881893, tzinfo=utc), verbose_name='보너스 참여일'),
        ),
    ]
