# Generated by Django 3.2 on 2021-05-22 07:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0019_auto_20210522_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='changed_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 7, 33, 22, 939574, tzinfo=utc), verbose_name='첫 참여날짜'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 7, 33, 22, 939574, tzinfo=utc), verbose_name='첫번째 참여일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fourth_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 7, 33, 22, 939574, tzinfo=utc), verbose_name='네번째 참여일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='plus_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 7, 33, 22, 939574, tzinfo=utc), verbose_name='보너스 참여일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 7, 33, 22, 939574, tzinfo=utc), verbose_name='두번째 참여일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='third_day',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 7, 33, 22, 939574, tzinfo=utc), verbose_name='세번째 참여일'),
        ),
    ]
