# Generated by Django 3.2 on 2021-05-26 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0023_auto_20210523_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='time',
            field=models.CharField(blank=True, choices=[('1', '평일'), ('2', '주말1시'), ('3', '주말4시')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='base_date',
            field=models.DateField(default=datetime.date(2021, 5, 26), verbose_name='기준 주차'),
        ),
        migrations.AlterField(
            model_name='student',
            name='changed_day',
            field=models.DateField(default=datetime.date(2021, 5, 26), verbose_name='첫 참여날짜'),
        ),
        migrations.AlterField(
            model_name='student',
            name='day1',
            field=models.DateField(default=datetime.date(2021, 5, 26), verbose_name='첫번째 참여일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='day2',
            field=models.DateField(default=datetime.date(2021, 5, 26), verbose_name='두번째 참여일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='day3',
            field=models.DateField(default=datetime.date(2021, 5, 26), verbose_name='세번째 참여일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='day4',
            field=models.DateField(default=datetime.date(2021, 5, 26), verbose_name='네번째 참여일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('1', '왕초급'), ('2', '초급'), ('3', '중급')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='plus_day',
            field=models.DateField(default=datetime.date(2021, 5, 26), verbose_name='보너스 참여일'),
        ),
    ]
