# Generated by Django 3.2.3 on 2021-05-29 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0025_auto_20210528_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='base_date',
            field=models.DateField(default=datetime.date(2021, 5, 29), verbose_name='기준 주차'),
        ),
        migrations.AlterField(
            model_name='student',
            name='changed_day',
            field=models.DateField(default=datetime.date(2021, 5, 29), verbose_name='등록하기 한날'),
        ),
        migrations.AlterField(
            model_name='student',
            name='day1',
            field=models.DateField(default=datetime.date(2021, 5, 29), verbose_name='첫번째 참여일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='day2',
            field=models.DateField(default=datetime.date(2021, 5, 29), verbose_name='두번째 참여일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='day3',
            field=models.DateField(default=datetime.date(2021, 5, 29), verbose_name='세번째 참여일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='day4',
            field=models.DateField(default=datetime.date(2021, 5, 29), verbose_name='네번째 참여일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='plus_day',
            field=models.DateField(default=datetime.date(2021, 5, 29), verbose_name='보너스 참여일'),
        ),
    ]
