# Generated by Django 3.2 on 2021-05-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_test_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='check',
            field=models.IntegerField(default=1),
        ),
    ]
