# Generated by Django 3.2 on 2021-05-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210504_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='age',
        ),
    ]
