# Generated by Django 3.2 on 2021-05-05 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_day',
            field=models.DateField(default=datetime.date(2021, 5, 6)),
        ),
        migrations.AddField(
            model_name='student',
            name='fixed_day',
            field=models.CharField(choices=[('1', '월요일'), ('2', '화요일'), ('3', '수요일'), ('4', '목요일'), ('5', '금요일'), ('6', '토요일'), ('7', '일요일')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='is_new',
            field=models.CharField(choices=[('o', '신규'), ('x', '재등록')], default='o', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='1', max_length=13),
            preserve_default=False,
        ),
    ]
