# Generated by Django 3.2 on 2021-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_auto_20210506_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_day',
            field=models.DateField(null=True),
        ),
    ]
