# Generated by Django 3.2 on 2021-05-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_auto_20210507_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='010-[0-9]{3,4}-[0-9]{4}'),
        ),
    ]
