# Generated by Django 3.2 on 2021-05-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_auto_20210511_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_new',
            field=models.CharField(choices=[('신규', '신규'), ('재등록', '재등록')], default='o', max_length=5, verbose_name='신규여부'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=10, verbose_name='성명'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='전화번호'),
        ),
    ]
